### ISSUE TITLE
KeyError: 'pose_crop'

### ISSUE THREAD

**Issue by coronet1127** [transpchan/Live3D-v2#1]
world_size: 0
batch_size: 1
local_rank:  0
skipping empty folder :./character_sheet/.ipynb_checkpoints
---building models...
---
test images:  100
---
Infer:   1%|▏                      | 1/100 [00:15<26:07, 15.83s/it, data_time=6.06, train_time=9.77]Traceback (most recent call last):
  File "train.py", line 225, in <module>
    test()
  File "train.py", line 82, in test
    infer(args, humanflowmodel, image_names_list)
  File "train.py", line 134, in infer
    str(int(data["imidx"].cpu().item())), pred_img, args.test_output_dir, crop=data["pose_crop"])
KeyError: 'pose_crop'
Infer:   1%|▏                      | 1/100 [00:16<27:31, 16.69s/it, data_time=6.06, train_time=9.77]

**Comment by transpchan** [comment]
That's strange. This usually happen when the input is completely empty. Could you check your pose input?
